src/Entity/Candidato.php
<?php

namespace App\Entity;

use App\Repository\CandidatoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CandidatoRepository::class)
 */
class Candidato
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cpf;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $primeiro_emprego;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $data_nascimento;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estado_civil;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sexo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_filhos;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $possui_decifiencia;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $carteira_habilitacao;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nacionalidade;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $naturalidade;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $foto;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cep;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logradouro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complemento;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bairro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cidade;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estado;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telefone1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $falarcom1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telefone2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $falarcom2;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="candidato", cascade={"persist", "remove"})
     */
    private $usuario;

    

    /**
     * @ORM\OneToMany(targetEntity=Experiencia::class, mappedBy="candidato")
     */
    private $experiencias;

    /**
     * @ORM\OneToMany(targetEntity=Formacao::class, mappedBy="candidato")
     */
    private $formacaos;

    /**
     * @ORM\OneToMany(targetEntity=Lingua::class, mappedBy="candidato")
     */
    private $linguas;

    /**
     * @ORM\OneToMany(targetEntity=Software::class, mappedBy="candidato")
     */
    private $softwares;

    /**
     * @ORM\OneToMany(targetEntity=CargoDesejado::class, mappedBy="candidato")
     */
    private $cargos_desejados;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $senha;

    public function __construct()
    {
        $this->experiencias = new ArrayCollection();
        $this->formacaos = new ArrayCollection();
        $this->linguas = new ArrayCollection();
        $this->softwares = new ArrayCollection();
        $this->cargos_desejados = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(?string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(?string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getPrimeiroEmprego(): ?bool
    {
        return $this->primeiro_emprego;
    }

    public function setPrimeiroEmprego(?bool $primeiro_emprego): self
    {
        $this->primeiro_emprego = $primeiro_emprego;

        return $this;
    }

    public function getDataNascimento(): ?\DateTimeInterface
    {
        return $this->data_nascimento;
    }

    public function setDataNascimento(?\DateTimeInterface $data_nascimento): self
    {
        $this->data_nascimento = $data_nascimento;

        return $this;
    }

    public function getEstadoCivil(): ?string
    {
        return $this->estado_civil;
    }

    public function setEstadoCivil(?string $estado_civil): self
    {
        $this->estado_civil = $estado_civil;

        return $this;
    }

    public function getSexo(): ?string
    {
        return $this->sexo;
    }

    public function setSexo(?string $sexo): self
    {
        $this->sexo = $sexo;

        return $this;
    }

    public function getNumeroFilhos(): ?string
    {
        return $this->numero_filhos;
    }

    public function setNumeroFilhos(?string $numero_filhos): self
    {
        $this->numero_filhos = $numero_filhos;

        return $this;
    }

    public function getPossuiDecifiencia(): ?bool
    {
        return $this->possui_decifiencia;
    }

    public function setPossuiDecifiencia(?bool $possui_decifiencia): self
    {
        $this->possui_decifiencia = $possui_decifiencia;

        return $this;
    }

    public function getCarteiraHabilitacao(): ?bool
    {
        return $this->carteira_habilitacao;
    }

    public function setCarteiraHabilitacao(?bool $carteira_habilitacao): self
    {
        $this->carteira_habilitacao = $carteira_habilitacao;

        return $this;
    }

    public function getNacionalidade(): ?string
    {
        return $this->nacionalidade;
    }

    public function setNacionalidade(?string $nacionalidade): self
    {
        $this->nacionalidade = $nacionalidade;

        return $this;
    }

    public function getNaturalidade(): ?string
    {
        return $this->naturalidade;
    }

    public function setNaturalidade(?string $naturalidade): self
    {
        $this->naturalidade = $naturalidade;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }

    public function getCep(): ?string
    {
        return $this->cep;
    }

    public function setCep(?string $cep): self
    {
        $this->cep = $cep;

        return $this;
    }

    public function getLogradouro(): ?string
    {
        return $this->logradouro;
    }

    public function setLogradouro(?string $logradouro): self
    {
        $this->logradouro = $logradouro;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(?string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getComplemento(): ?string
    {
        return $this->complemento;
    }

    public function setComplemento(?string $complemento): self
    {
        $this->complemento = $complemento;

        return $this;
    }

    public function getBairro(): ?string
    {
        return $this->bairro;
    }

    public function setBairro(?string $bairro): self
    {
        $this->bairro = $bairro;

        return $this;
    }

    public function getCidade(): ?string
    {
        return $this->cidade;
    }

    public function setCidade(?string $cidade): self
    {
        $this->cidade = $cidade;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(?string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getTelefone1(): ?string
    {
        return $this->telefone1;
    }

    public function setTelefone1(?string $telefone1): self
    {
        $this->telefone1 = $telefone1;

        return $this;
    }

    public function getFalarcom1(): ?string
    {
        return $this->falarcom1;
    }

    public function setFalarcom1(?string $falarcom1): self
    {
        $this->falarcom1 = $falarcom1;

        return $this;
    }

    public function getTelefone2(): ?string
    {
        return $this->telefone2;
    }

    public function setTelefone2(?string $telefone2): self
    {
        $this->telefone2 = $telefone2;

        return $this;
    }

    public function getFalarcom2(): ?string
    {
        return $this->falarcom2;
    }

    public function setFalarcom2(?string $falarcom2): self
    {
        $this->falarcom2 = $falarcom2;

        return $this;
    }

    public function getUsuario(): ?User
    {
        return $this->usuario;
    }

    public function setUsuario(?User $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    

    /**
     * @return Collection|Experiencia[]
     */
    public function getExperiencias(): Collection
    {
        return $this->experiencias;
    }

    public function addExperiencia(Experiencia $experiencia): self
    {
        if (!$this->experiencias->contains($experiencia)) {
            $this->experiencias[] = $experiencia;

src/Entity/CargoDesejado.php
<?php

namespace App\Entity;

use App\Repository\CargoDesejadoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CargoDesejadoRepository::class)
 */
class CargoDesejado
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Candidato::class, inversedBy="cargos_desejados")
     */
    private $candidato;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cargo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pretencao_salarial;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCandidato(): ?Candidato
    {
        return $this->candidato;
    }

    public function setCandidato(?Candidato $candidato): self
    {
        $this->candidato = $candidato;

        return $this;
    }

    public function getCargo(): ?string
    {
        return $this->cargo;
    }

    public function setCargo(?string $cargo): self
    {
        $this->cargo = $cargo;

        return $this;
    }

    public function getPretencaoSalarial(): ?string
    {
        return $this->pretencao_salarial;
    }

    public function setPretencaoSalarial(?string $pretencao_salarial): self
    {
        $this->pretencao_salarial = $pretencao_salarial;

        return $this;
    }
}

src/Entity/Experiencia.php
<?php

namespace App\Entity;

use App\Repository\ExperienciaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExperienciaRepository::class)
 */
class Experiencia
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Candidato::class, inversedBy="experiencias")
     */
    private $candidato;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $empresa;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ultimo_cargo;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $data_admissao;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $data_demissao;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ultimo_salario;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $atividade_exercida;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCandidato(): ?Candidato
    {
        return $this->candidato;
    }

    public function setCandidato(?Candidato $candidato): self
    {
        $this->candidato = $candidato;

        return $this;
    }

    public function getEmpresa(): ?string
    {
        return $this->empresa;
    }

    public function setEmpresa(?string $empresa): self
    {
        $this->empresa = $empresa;

        return $this;
    }

    public function getUltimoCargo(): ?string
    {
        return $this->ultimo_cargo;
    }

    public function setUltimoCargo(?string $ultimo_cargo): self
    {
        $this->ultimo_cargo = $ultimo_cargo;

        return $this;
    }

    public function getDataAdmissao(): ?\DateTimeInterface
    {
        return $this->data_admissao;
    }

    public function setDataAdmissao(?\DateTimeInterface $data_admissao): self
    {
        $this->data_admissao = $data_admissao;

        return $this;
    }

    public function getDataDemissao(): ?\DateTimeInterface
    {
        return $this->data_demissao;
    }

    public function setDataDemissao(?\DateTimeInterface $data_demissao): self
    {
        $this->data_demissao = $data_demissao;

        return $this;
    }

    public function getUltimoSalario(): ?string
    {
        return $this->ultimo_salario;
    }

    public function setUltimoSalario(?string $ultimo_salario): self
    {
        $this->ultimo_salario = $ultimo_salario;

        return $this;
    }

    public function getAtividadeExercida(): ?string
    {
        return $this->atividade_exercida;
    }

    public function setAtividadeExercida(?string $atividade_exercida): self
    {
        $this->atividade_exercida = $atividade_exercida;

        return $this;
    }
}

src/Entity/Lingua.php
<?php

namespace App\Entity;

use App\Repository\LinguaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LinguaRepository::class)
 */
class Lingua
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Candidato::class, inversedBy="linguas")
     */
    private $candidato;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descricao;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nivel_fluencia;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCandidato(): ?Candidato
    {
        return $this->candidato;
    }

    public function setCandidato(?Candidato $candidato): self
    {
        $this->candidato = $candidato;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(?string $descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getNivelFluencia(): ?string
    {
        return $this->nivel_fluencia;
    }

    public function setNivelFluencia(?string $nivel_fluencia): self
    {
        $this->nivel_fluencia = $nivel_fluencia;

        return $this;
    }
}

templates/candidato/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidato/desejado.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CargoDesejado{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="page-subheading page-subheading-md">
            <ol class="breadcrumb">
                <li class="active"><a href="javascript:;">Editar Candidatos</a></li>
            </ol>
        </div>

        <div class="container-fluid-md">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Formulário</h4>
                        </div>
                        <div class="panel-body">
                            {{ form_start(form) }}
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-3">
                                <div class="form-group">
                                    {{ form_label(form.cargo, "Cargo", { 'attr': { 'class': 'control-label'}} ) }}
                                    {{ form_errors(form.cargo) }}
                                    {{ form_widget(form.cargo, { 'attr': { 'class': 'form-control'}} ) }}
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6 col-lg-3">
                                <div class="form-group">
                                    {{ form_label(form.pretencao_salarial, "Pretensão Salarial", { 'attr': { 'class': 'control-label'}} ) }}
                                    {{ form_errors(form.pretencao_salarial) }}
                                    {{ form_widget(form.pretencao_salarial, { 'attr': { 'class': 'form-control'}} ) }}
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                                <div class="col-md-12">                            
                                    {{ include('cargo_desejado/_form.html.twig', {'button_label': 'Salvar'}) }}
                                
                                    <a class="btn btn-inverse" href="{{ path('cargo_desejado_index') }}">Voltar</a>
                                </div>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/candidato/experiencia.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Experiencia{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="page-subheading page-subheading-md">
            <ol class="breadcrumb">
                <li class="active"><a href="javascript:;">Experiência</a></li>
            </ol>
        </div>

        <div class="container-fluid-md">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Formulário</h4>
                        </div>
                        <div class="panel-body">
                            {{ form_start(form) }}
                        <div class="row">
                        <div class="col-sm-12 col-md-6 col-lg-3">
                            <div class="form-group">
                                {{ form_label(form.empresa, "Empresa", { 'attr': { 'class': 'control-label'}} ) }}
                                {{ form_errors(form.empresa) }}
                                {{ form_widget(form.empresa, { 'attr': { 'class': 'form-control'}} ) }}
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6 col-lg-3">
                            <div class="form-group">
                                {{ form_label(form.ultimo_cargo, "Último Cargo", { 'attr': { 'class': 'control-label'}} ) }}
                                {{ form_errors(form.ultimo_cargo) }}
                                {{ form_widget(form.ultimo_cargo, { 'attr': { 'class': 'form-control'}} ) }}
                            </div>
                        </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-3">
                                <div class="form-group">
                                    {{ form_label(form.data_admissao, "Data de Admissao", { 'attr': { 'class': 'control-label'}} ) }}
                                    {{ form_errors(form.data_admissao) }}
                                    {{ form_widget(form.data_admissao, { 'attr': { 'class': 'form-control'}} ) }}
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6 col-lg-3">
                                <div class="form-group">
                                    {{ form_label(form.data_demissao, "Data de Demissao", { 'attr': { 'class': 'control-label'}} ) }}
                                    {{ form_errors(form.data_demissao) }}
                                    {{ form_widget(form.data_demissao, { 'attr': { 'class': 'form-control'}} ) }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-3">
                                <div class="form-group">
                                    {{ form_label(form.ultimo_salario, "Último Salário", { 'attr': { 'class': 'control-label'}} ) }}
                                    {{ form_errors(form.ultimo_salario) }}
                                    {{ form_widget(form.ultimo_salario, { 'attr': { 'class': 'form-control'}} ) }}
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6 col-lg-3">
                                <div class="form-group">
                                    {{ form_label(form.atividade_exercida, "Atividade Exercida", { 'attr': { 'class': 'control-label'}} ) }}
                                    {{ form_errors(form.atividade_exercida) }}
                                    {{ form_widget(form.atividade_exercida, { 'attr': { 'class': 'form-control'}} ) }}
                                </div>
                            </div>
                        </div>                     

                        <div class="row">
                            <div class="col-md-12">                            
                                {{ include('experiencia/_form.html.twig', {'button_label': 'Salvar'}) }}
                                    
                                <a class="btn btn-inverse" href="{{ path('experiencia_index') }}">Voltar</a>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>                        
                </div>                    
            </div>
        </div>            
    </div>  
{% endblock %}

templates/candidato/mostrar_desejado.html.twig
{% extends 'base.html.twig' %}

{% block title %}CargoDesejado{% endblock %}

{% block body %}
    <div class="page-content">
            <div class="page-subheading page-subheading-md">
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="javascript:;">Área</a>
                    </li>
                </ol>
            </div>

        <div class="container-fluid-md">
            <a class="btn btn-inverse" href="{{ path('candidato_edit', {'id': candidato.id}) }}">Voltar</a>            

            <a class="btn btn-primary" href="{{ path('candidato_editar_desejado', {'desejado': desejado.id, 'candidato' : candidato.id}) }}">Editar</a>
        </div>           

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ desejado.id }}</td>
                </tr>
                <tr>
                    <th>Cargo</th>
                    <td>{{ desejado.cargo }}</td>
                </tr>
                <tr>
                    <th>Pretencao_salarial</th>
                    <td>{{ desejado.pretencaoSalarial }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/candidato/mostrar_experiencia.html.twig
{% extends 'base.html.twig' %}

{% block title %}Experiencia{% endblock %}

{% block body %}
    <div class="page-content">
            <div class="page-subheading page-subheading-md">
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="javascript:;">Área</a>
                    </li>
                </ol>
            </div>

        <div class="container-fluid-md">
            <a class="btn btn-inverse" href="{{ path('candidato_edit', {'id': candidato.id}) }}">Voltar</a>            

            <a class="btn btn-primary" href="{{ path('candidato_editar_experiencia', {'experiencia': experiencia.id, 'candidato' : candidato.id}) }}">Editar</a>

            

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ experiencia.id }}</td>
                </tr>
                <tr>
                    <th>Empresa</th>
                    <td>{{ experiencia.empresa }}</td>
                </tr>
                <tr>
                    <th>Ultimo_cargo</th>
                    <td>{{ experiencia.ultimoCargo }}</td>
                </tr>
                <tr>
                    <th>Data_admissao</th>
                    <td>{{ experiencia.dataAdmissao ? experiencia.dataAdmissao|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Data_demissao</th>
                    <td>{{ experiencia.dataDemissao ? experiencia.dataDemissao|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Ultimo_salario</th>
                    <td>{{ experiencia.ultimoSalario }}</td>
                </tr>
                <tr>
                    <th>Atividade_exercida</th>
                    <td>{{ experiencia.atividadeExercida }}</td>
                </tr>
            </tbody>
        </table>    
    </div>

{% endblock %}

templates/candidato/mostrar_lingua.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lingua{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="page-subheading page-subheading-md">
            <ol class="breadcrumb">
                <li class="active">
                    <a href="javascript:;">Língua</a>
                </li>
            </ol>
        </div>

        <div class="container-fluid-md">
            <a class="btn btn-inverse" href="{{ path('candidato_edit', {'id': candidato.id}) }}">Voltar</a>            

            <a class="btn btn-primary" href="{{ path('candidato_editar_lingua', {'lingua': lingua.id, 'candidato' : candidato.id}) }}">Editar</a>
            
            <table class="table">
                <tbody>   
                    <tr>
                        <th>Id</th>
                        <td>{{ lingua.id }}</td>
                    </tr>         
                    <tr>
                        <th>Descricao</th>
                        <td>{{ lingua.descricao }}</td>
                    </tr>
                    <tr>
                        <th>Nivel_fluencia</th>
                        <td>{{ lingua.nivelFluencia }}</td>
                    </tr>
                </tbody>
            </table>    
        </div>
    </div>


{% endblock %}

templates/candidato/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidato{% endblock %}

{% block body %}
    <div class="page-content">
            <div class="page-subheading page-subheading-md">
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="javascript:;">Candidato</a>
                    </li>
                </ol>
            </div>

        <div class="container-fluid-md">
            <a class="btn btn-inverse" href="{{ path('candidato_index') }}">Voltar</a>            

            <a class=" btn btn-primary" href="{{ path('candidato_edit', {'id': candidato.id}) }}">Editar</a>
            <br></br>

            {{ include('candidato/_delete_form.html.twig') }}

        
        

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidato.id }}</td>
            </tr>
            <tr>
                <th>Nome</th>
                <td>{{ candidato.nome }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ candidato.email }}</td>
            </tr>
            <tr>
                <th>Cpf</th>
                <td>{{ candidato.cpf }}</td>
            </tr>
            <tr>
                <th>Primeiro_emprego</th>
                <td>{{ candidato.primeiroEmprego ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Data_nascimento</th>
                <td>{{ candidato.dataNascimento ? candidato.dataNascimento|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Estado_civil</th>
                <td>{{ candidato.estadoCivil }}</td>
            </tr>
            <tr>
                <th>Sexo</th>
                <td>{{ candidato.sexo }}</td>
            </tr>
            <tr>
                <th>Numero_filhos</th>
                <td>{{ candidato.numeroFilhos }}</td>
            </tr>
            <tr>
                <th>Possui_decifiencia</th>
                <td>{{ candidato.possuiDecifiencia ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Carteira_habilitacao</th>
                <td>{{ candidato.carteiraHabilitacao ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Nacionalidade</th>
                <td>{{ candidato.nacionalidade }}</td>
            </tr>
            <tr>
                <th>Naturalidade</th>
                <td>{{ candidato.naturalidade }}</td>
            </tr>
            <tr>
                <th>Foto</th>
                <td>{{ candidato.foto }}</td>
            </tr>
            <tr>
                <th>Cep</th>
                <td>{{ candidato.cep }}</td>
            </tr>
            <tr>
                <th>Logradouro</th>
                <td>{{ candidato.logradouro }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ candidato.numero }}</td>
            </tr>
            <tr>
                <th>Complemento</th>
                <td>{{ candidato.complemento }}</td>
            </tr>
            <tr>
                <th>Bairro</th>
                <td>{{ candidato.bairro }}</td>
            </tr>
            <tr>
                <th>Cidade</th>
                <td>{{ candidato.cidade }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ candidato.estado }}</td>
            </tr>
            <tr>
                <th>Telefone1</th>
                <td>{{ candidato.telefone1 }}</td>
            </tr>
            <tr>
                <th>Falarcom1</th>
                <td>{{ candidato.falarcom1 }}</td>
            </tr>
            <tr>
                <th>Telefone2</th>
                <td>{{ candidato.telefone2 }}</td>
            </tr>
            <tr>
                <th>Falarcom2</th>
                <td>{{ candidato.falarcom2 }}</td>
            </tr>
        </tbody>
    </table>
    </div>
    

    
    </div>
{% endblock %}