src/Entity/Formacao.php
<?php

namespace App\Entity;

use App\Repository\FormacaoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormacaoRepository::class)
 */
class Formacao
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Candidato::class, inversedBy="formacao")
     */
    private $candidato;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $grau_formacao;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $curso;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instituicao;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $situacao;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $data_conclusao;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCandidato(): ?Candidato
    {
        return $this->candidato;
    }

    public function setCandidato(?Candidato $candidato): self
    {
        $this->candidato = $candidato;

        return $this;
    }

    public function getGrauFormacao(): ?string
    {
        return $this->grau_formacao;
    }

    public function setGrauFormacao(?string $grau_formacao): self
    {
        $this->grau_formacao = $grau_formacao;

        return $this;
    }

    public function getCurso(): ?string
    {
        return $this->curso;
    }

    public function setCurso(?string $curso): self
    {
        $this->curso = $curso;

        return $this;
    }

    public function getInstituicao(): ?string
    {
        return $this->instituicao;
    }

    public function setInstituicao(?string $instituicao): self
    {
        $this->instituicao = $instituicao;

        return $this;
    }

    public function getSituacao(): ?string
    {
        return $this->situacao;
    }

    public function setSituacao(?string $situacao): self
    {
        $this->situacao = $situacao;

        return $this;
    }

    public function getDataConclusao(): ?\DateTimeInterface
    {
        return $this->data_conclusao;
    }

    public function setDataConclusao(?\DateTimeInterface $data_conclusao): self
    {
        $this->data_conclusao = $data_conclusao;

        return $this;
    }
}

src/Form/FormacaoType.php
<?php

namespace App\Form;

use App\Entity\Candidato;
use App\Entity\Formacao;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class FormacaoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('grau_formacao')
            ->add('curso')
            ->add('instituicao')
            ->add('situacao')
            ->add('data_conclusao', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('candidato', EntityType::class, [
                'class' => Candidato::class,
                'choice_label' => 'nome',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formacao::class,
        ]);
    }
}

src/Controller/FormacaoController.php
<?php

namespace App\Controller;

use App\Entity\Formacao;
use App\Form\FormacaoType;
use App\Repository\FormacaoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/formacao")
 */
class FormacaoController extends AbstractController
{
    /**
     * @Route("/", name="formacao_index", methods={"GET"})
     */
    public function index(FormacaoRepository $formacaoRepository): Response
    {
        return $this->render('formacao/index.html.twig', [
            'formacaos' => $formacaoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formacao_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $formacao = new Formacao();
        $form = $this->createForm(FormacaoType::class, $formacao);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formacao);
            $entityManager->flush();

            return $this->redirectToRoute('formacao_index');
        }

        return $this->render('formacao/new.html.twig', [
            'formacao' => $formacao,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formacao_show", methods={"GET"})
     */
    public function show(Formacao $formacao): Response
    {
        return $this->render('formacao/show.html.twig', [
            'formacao' => $formacao,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formacao_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formacao $formacao): Response
    {
        $form = $this->createForm(FormacaoType::class, $formacao);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formacao_index');
        }

        return $this->render('formacao/edit.html.twig', [
            'formacao' => $formacao,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formacao_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formacao $formacao): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formacao->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formacao);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formacao_index');
    }
}

templates/formacao/_delete_form.html.twig
<form style="display: none;" method="post" action="{{ path('formacao_delete', {'id': formacao.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formacao.id) }}">
    <button id="deleteSubmit" class="btn btn-danger">Deletar</button>
</form>

templates/formacao/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/formacao/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formacao{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="page-subheading page-subheading-md">
            <ol class="breadcrumb">
                <li class="active"><a href="javascript:;">Editar Formação</a></li>
            </ol>
        </div>

        <div class="container-fluid-md">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Formulário</h4>                    
                            
                        </div>
                        <div class="panel-body">
                            {{ form_start(form) }}
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.grau_formacao, "Grau de Formacao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.grau_formacao) }}
                                        {{ form_widget(form.grau_formacao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.curso, "Curso", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.curso) }}
                                        {{ form_widget(form.curso, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.instituicao, "Instituicao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.instituicao) }}
                                        {{ form_widget(form.instituicao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.situacao, "Situacao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.situacao) }}
                                        {{ form_widget(form.situacao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.data_conclusao, "Data de Conclusao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.data_conclusao) }}
                                        {{ form_widget(form.data_conclusao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.candidato, "Candidato", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.candidato) }}
                                        {{ form_widget(form.candidato, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">                            
                                    {{ include('formacao/_form.html.twig', {'button_label': 'Salvar'}) }}
                                
                                    <a class="btn btn-inverse" href="{{ path('formacao_index') }}">Voltar</a>
                                
                                    <a class="btn btn-danger" onclick="deletar();">Deletar</a>
                                </div>
                            </div>
                            {{ form_end(form) }}

                            {{ include('formacao/_delete_form.html.twig') }}
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>
{% endblock %}

{% block javascripts %} 
    {{ parent() }}
    <script>
        function deletar() {
            $("#deleteSubmit").click();
        }
    </script>
{% endblock %}

templates/formacao/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formacao index{% endblock %}

{% block body %}
    <div class="page-content">
            <div class="page-subheading page-subheading-md">
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="javascript:;">Formação</a>
                    </li>
                </ol>
            </div>

            <div class="container-fluid-md">
            <a class="btn btn-primary" href="{{ path('formacao_new') }}">Cadastrar</a>
            <br></br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Formação</h4>            
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th width="9%">Id</th>
                        <th width="9%">Curso</th>
                        <th width="9%">Situacao</th>
                        <th width="9%">Data de Conclusao</th>
                        <th width="9%">Ações</th>
                    </tr>
                </thead>
                <tbody>
                {% for formacao in formacaos %}
                    <tr>
                        <td>{{ formacao.id }}</td>
                        <td>{{ formacao.curso }}</td>
                        <td>{{ formacao.situacao }}</td>
                        <td>{{ formacao.dataConclusao ? formacao.dataConclusao|date('d-m-Y') : '' }}</td>
                <td>
                        
                        <td>
                            <a class=" btn btn-success" href="{{ path('formacao_show', {'id': formacao.id}) }}">Mostrar</a>
                            <a class="btn btn-inverse" href="{{ path('formacao_edit', {'id': formacao.id}) }}">Editar</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="26">Sem registros</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

templates/formacao/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formacao{% endblock %}

{% block body %}
    <div class="page-content">
            <div class="page-subheading page-subheading-md">
                <ol class="breadcrumb">
                    <li class="active"><a href="javascript:;">Cadastro de Formação</a></li>
                </ol>
            </div>


            <div class="container-fluid-md">
            
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Formulário</h4>                    
                    
                </div>
                <div class="panel-body">
                    {{ form_start(form) }}
                        <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.grau_formacao, "Grau de Formacao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.grau_formacao) }}
                                        {{ form_widget(form.grau_formacao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.curso, "Curso", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.curso) }}
                                        {{ form_widget(form.curso, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.instituicao, "Instituicao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.instituicao) }}
                                        {{ form_widget(form.instituicao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.situacao, "Situacao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.situacao) }}
                                        {{ form_widget(form.situacao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.data_conclusao, "Data de Conclusao", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.data_conclusao) }}
                                        {{ form_widget(form.data_conclusao, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        {{ form_label(form.candidato, "Candidato", { 'attr': { 'class': 'control-label'}} ) }}
                                        {{ form_errors(form.candidato) }}
                                        {{ form_widget(form.candidato, { 'attr': { 'class': 'form-control'}} ) }}
                                    </div>
                                </div>
                            </div>
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Enviar</button>
    <a class="btn btn-inverse" href="{{ path('formacao_index') }}">Voltar</a>
    {{ form_end(form) }}
    </div>
    
{% endblock %}

templates/formacao/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formacao{% endblock %}

{% block body %}
    <div class="page-content">
            <div class="page-subheading page-subheading-md">
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="javascript:;">Formação</a>
                    </li>
                </ol>
            </div>

        <div class="container-fluid-md">
            <a class="btn btn-inverse" href="{{ path('formacao_index') }}">Voltar</a>            

            <a class=" btn btn-primary" href="{{ path('formacao_edit', {'id': formacao.id}) }}">Editar</a>            
            <br></br>
            {{ include('formacao/_delete_form.html.twig') }}

            

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formacao.id }}</td>
            </tr>
            <tr>
                <th>Grau de Formacão</th>
                <td>{{ formacao.grauFormacao }}</td>
            </tr>
            <tr>
                <th>Curso</th>
                <td>{{ formacao.curso }}</td>
            </tr>
            <tr>
                <th>Instituição</th>
                <td>{{ formacao.instituicao }}</td>
            </tr>
            <tr>
                <th>Situacao</th>
                <td>{{ formacao.situacao }}</td>
            </tr>
            <tr>
                <th>Data de Conclusão</th>
                <td>{{ formacao.dataConclusao ? formacao.dataConclusao|date('d-m-y') : '' }}</td>
            </tr>
        </tbody>
    </table>
    
    </div>


{% endblock %}